name = "python-sdk"
engineVersion = "v1.0.0-beta.11"
include = ["!runtime", "!.dagger", "!future", "!docs"]

[runtime]
source = "dang"

[[dependencies]]
name = "sdk-helpers"
source = "dagger.io/sdk/helpers@v1"
