name = "python-sdk"
engineVersion = "v1.0.0-beta.14"
include = ["!.dagger", "!future", "!docs"]

[runtime]
source = "dang"

[[dependencies]]
name = "sdk-helpers"
source = "github.com/dagger/sdk-helpers@v1.0.6"

[[dependencies]]
name = "python-sdk-runtime"
source = "runtime"
