"""Generated clients for the modules this library is bound to.

Every module in this package is generated by the Python SDK: one per bound
module, named after it. Nothing here is written by hand.
"""
