# Code generated by dagger. DO NOT EDIT.

import warnings  # noqa: F401
from collections.abc import Callable  # noqa: F401
from dataclasses import dataclass  # noqa: F401
from typing import Protocol, runtime_checkable  # noqa: F401

from typing_extensions import Self  # noqa: F401

from dagger.client import gen as _core
from dagger.client._binding import ModuleBinding
from dagger.client._core import Arg
from dagger.client._guards import typecheck
from dagger.client.base import Enum, Input, Scalar, Type  # noqa: F401


_BINDING = ModuleBinding(
    name='runtime-app',
    kind='LOCAL_SOURCE',
    ref='/.dagger/modules/e2e/fixtures/runtime/app',
    pin='',
)

@typecheck
class RuntimeApp(Type):

    async def greeting(self) -> str:
        """Returns
        -------
        str
            The `String` scalar type represents textual data, represented as
            UTF-8 character sequences. The String type is most often used by
            GraphQL to represent free-form human-readable text.

        Raises
        ------
        ExecuteTimeoutError
            If the time to execute the query exceeds the configured timeout.
        QueryError
            If the API returns an error.
        """
        _args: list[Arg] = []
        _ctx = self._select("greeting", _args)
        return await _ctx.execute(str)

    async def id(self) -> str:
        """A unique identifier for this RuntimeApp.

        Note
        ----
        This is lazily evaluated, no operation is actually run.

        Returns
        -------
        str
            The `ID` scalar type represents a unique identifier, often used to
            refetch an object or as key for a cache. The ID type appears in a
            JSON response as a String; however, it is not intended to be
            human-readable. When expected as an input type, any string (such
            as `"4"`) or integer (such as `4`) input value will be accepted as
            an ID.

        Raises
        ------
        ExecuteTimeoutError
            If the time to execute the query exceeds the configured timeout.
        QueryError
            If the API returns an error.
        """
        _args: list[Arg] = []
        _ctx = self._select("id", _args)
        return await _ctx.execute(str)



def runtime_app(*, client: _core.Client | None = None) -> RuntimeApp:
    """Client for the `runtime-app` module.

    Executing any query through the returned object serves the module into
    the session first; a module bound by workspace path needs a workspace,
    a module bound by git ref resolves anywhere. Pass `client` to use a
    connection other than the global one.
    """
    _args: list[Arg] = []
    _ctx = (_core.dag if client is None else client)._ctx.with_binding(_BINDING).root_select("runtimeApp", _args)  # noqa: SLF001
    return RuntimeApp(_ctx)

__all__ = [
    "RuntimeApp",
    "runtime_app",
]