// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Functions for building the runtime module for the Python SDK.
//
// The server interacts directly with ModuleRuntime. The others were built to be
// composable and chainable to facilitate the creation of extension modules
// (custom SDKs that depend on this one).
type PythonSDKRuntime struct { // python-sdk-runtime (../../../:0:0)
	query *querybuilder.Selection

	baseImage      *string
	contextDirPath *string
	debug          *bool
	extraIndexUrl  *string
	id             *ID
	indexUrl       *string
	isInit         *bool
	mainObjectName *string
	modName        *string
	packageName    *string
	projectName    *string
	subPath        *string
	useUv          *bool
	useUvLock      *bool
	uvImage        *string
	uvVersion      *string
	vendorPath     *string
}
type WithPythonSDKRuntimeFunc func(r *PythonSDKRuntime) *PythonSDKRuntime

// With calls the provided function with current PythonSDKRuntime.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *PythonSDKRuntime) With(f WithPythonSDKRuntimeFunc) *PythonSDKRuntime {
	return f(r)
}

func (r *PythonSDKRuntime) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKRuntime {
	return &PythonSDKRuntime{
		query: q,
	}
}

// Image reference for the base container
func (r *PythonSDKRuntime) BaseImage(ctx context.Context) (string, error) {
	if r.baseImage != nil {
		return *r.baseImage, nil
	}
	q := r.query.Select("baseImage")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Resulting container after each composing step
func (r *PythonSDKRuntime) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// ContextDir is a copy of the context directory from the module source
//
// We add files to this directory, always joining paths with the source's
// subpath. We could use modSource.Directory("") for that if it was read-only,
// but since we have to mount the context directory in the end, rather than
// mounting the context dir and then mounting the forked source dir on top,
// we fork the context dir instead so there's only one mount in the end.
func (r *PythonSDKRuntime) ContextDir() *Directory {
	q := r.query.Select("contextDir")

	return &Directory{
		query: q,
	}
}

// ContextDirPath is a unique host path for the module being loaded
//
// HACK: this property is computed as a unique value for a ModuleSource to
// provide a unique path on the filesystem. This is because the uv cache
// uses hashes of source paths - so we need to have something unique, or we
// can get very real conflicts in the uv cache.
func (r *PythonSDKRuntime) ContextDirPath(ctx context.Context) (string, error) {
	if r.contextDirPath != nil {
		return *r.contextDirPath, nil
	}
	q := r.query.Select("contextDirPath")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Whether the module runtime should run in debug mode.
func (r *PythonSDKRuntime) Debug(ctx context.Context) (bool, error) {
	if r.debug != nil {
		return *r.debug, nil
	}
	q := r.query.Select("debug")

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Uv's "extra-index-url" setting
func (r *PythonSDKRuntime) ExtraIndexURL(ctx context.Context) (string, error) {
	if r.extraIndexUrl != nil {
		return *r.extraIndexUrl, nil
	}
	q := r.query.Select("extraIndexUrl")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GetFile returns a file from the module's source.
func (r *PythonSDKRuntime) GetFile(name string) *File {
	q := r.query.Select("getFile")
	q = q.Arg("name", name)

	return &File{
		query: q,
	}
}

// A unique identifier for this PythonSdkRuntime.
func (r *PythonSDKRuntime) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKRuntime) XXX_GraphQLType() string {
	return "PythonSdkRuntime"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKRuntime) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKRuntime) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKRuntime) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKRuntime) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PythonSDKRuntime{query: selectNode(dag.query, id, "PythonSdkRuntime")}
	return nil
}

// Uv's default index URL setting
func (r *PythonSDKRuntime) IndexURL(ctx context.Context) (string, error) {
	if r.indexUrl != nil {
		return *r.indexUrl, nil
	}
	q := r.query.Select("indexUrl")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// True if the module is new and we need to create files from the template
//
// It's assumed that this is the case if there's no pyproject.toml file.
func (r *PythonSDKRuntime) IsInit(ctx context.Context) (bool, error) {
	if r.isInit != nil {
		return *r.isInit, nil
	}
	q := r.query.Select("isInit")

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Get all the needed information from the module's metadata and source files
func (r *PythonSDKRuntime) Load(modSource *ModuleSource) *PythonSDKRuntime {
	assertNotNil("modSource", modSource)
	q := r.query.Select("load")
	q = q.Arg("modSource", modSource)

	return &PythonSDKRuntime{
		query: q,
	}
}

// The normalized main object name in Python
func (r *PythonSDKRuntime) MainObjectName(ctx context.Context) (string, error) {
	if r.mainObjectName != nil {
		return *r.mainObjectName, nil
	}
	q := r.query.Select("mainObjectName")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// The original module's name
func (r *PythonSDKRuntime) ModName(ctx context.Context) (string, error) {
	if r.modName != nil {
		return *r.modName, nil
	}
	q := r.query.Select("modName")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// The source needed to load and run a module
func (r *PythonSDKRuntime) ModSource() *ModuleSource {
	q := r.query.Select("modSource")

	return &ModuleSource{
		query: q,
	}
}

// PythonSDKRuntimeModuleRuntimeOpts contains options for PythonSDKRuntime.ModuleRuntime
type PythonSDKRuntimeModuleRuntimeOpts struct {
	IntrospectionJSON *File
}

// Container for executing the Python module runtime
//
// The container is built from the module's committed generated files. This
// runtime generates nothing: code generation belongs to `dagger generate`,
// which the Python SDK module owns. Dependencies are still installed — the
// language-level assemble step, like the Go SDK still running go build.
//
// introspectionJSON is declared, and never read, on purpose: its optionality is
// the signal the engine reads (RuntimeTrustsCommittedFiles) to decide it may
// skip runtime codegen and omit the argument altogether. Dropping the argument
// would tell the engine the opposite. It is the opt-out, not a code path.
func (r *PythonSDKRuntime) ModuleRuntime(modSource *ModuleSource, opts ...PythonSDKRuntimeModuleRuntimeOpts) *Container {
	assertNotNil("modSource", modSource)
	q := r.query.Select("moduleRuntime")
	for i := len(opts) - 1; i >= 0; i-- {
		// `introspectionJson` optional argument
		if !querybuilder.IsZeroValue(opts[i].IntrospectionJSON) {
			q = q.Arg("introspectionJson", opts[i].IntrospectionJSON)
		}
	}
	q = q.Arg("modSource", modSource)

	return &Container{
		query: q,
	}
}

// The normalized python import package name (in the filesystem)
func (r *PythonSDKRuntime) PackageName(ctx context.Context) (string, error) {
	if r.packageName != nil {
		return *r.packageName, nil
	}
	q := r.query.Select("packageName")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// The normalized python distribution package name (in pyproject.toml)
func (r *PythonSDKRuntime) ProjectName(ctx context.Context) (string, error) {
	if r.projectName != nil {
		return *r.projectName, nil
	}
	q := r.query.Select("projectName")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// We could use modSource.Directory("") but we'll need to use the
// context directory later, so rather than trying
// to replace the source directory in the context directory, we'll
// just use the context directory with subpath everywhere.
func (r *PythonSDKRuntime) Source() *Directory {
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// Relative path from the context directory to the source directory
func (r *PythonSDKRuntime) SubPath(ctx context.Context) (string, error) {
	if r.subPath != nil {
		return *r.subPath, nil
	}
	q := r.query.Select("subPath")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Check whether to use uv or not
func (r *PythonSDKRuntime) UseUv(ctx context.Context) (bool, error) {
	if r.useUv != nil {
		return *r.useUv, nil
	}
	q := r.query.Select("useUv")

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// UseUvLock returns true if the runtime should expect a uv.lock file.
func (r *PythonSDKRuntime) UseUvLock(ctx context.Context) (bool, error) {
	if r.useUvLock != nil {
		return *r.useUvLock, nil
	}
	q := r.query.Select("useUvLock")

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Image reference where uv is fetched from
func (r *PythonSDKRuntime) UvImage(ctx context.Context) (string, error) {
	if r.uvImage != nil {
		return *r.uvImage, nil
	}
	q := r.query.Select("uvImage")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Version to use for uv
func (r *PythonSDKRuntime) UvVersion(ctx context.Context) (string, error) {
	if r.uvVersion != nil {
		return *r.uvVersion, nil
	}
	q := r.query.Select("uvVersion")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Relative path to vendor client library into
func (r *PythonSDKRuntime) VendorPath(ctx context.Context) (string, error) {
	if r.vendorPath != nil {
		return *r.vendorPath, nil
	}
	q := r.query.Select("vendorPath")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Initialize the base Python container
//
// Workdir is set to the module's source directory.
func (r *PythonSDKRuntime) WithBase() *PythonSDKRuntime {
	q := r.query.Select("withBase")

	return &PythonSDKRuntime{
		query: q,
	}
}

// Override the base container's image
//
// Needs to be called before Load.
func (r *PythonSDKRuntime) WithBaseImage(ref string) *PythonSDKRuntime {
	q := r.query.Select("withBaseImage")
	q = q.Arg("ref", ref)

	return &PythonSDKRuntime{
		query: q,
	}
}

// Replace the underlying container
//
// Since all steps change this container, it's possible to extract it in one
// step, change it, and then set it with this function. Can be useful, for
// example, to add system packages between the WithBase() and WithSource()
// steps.
func (r *PythonSDKRuntime) WithContainer(ctr *Container) *PythonSDKRuntime {
	assertNotNil("ctr", ctr)
	q := r.query.Select("withContainer")
	q = q.Arg("ctr", ctr)

	return &PythonSDKRuntime{
		query: q,
	}
}

// Install the module's package and dependencies
func (r *PythonSDKRuntime) WithInstall() *PythonSDKRuntime {
	q := r.query.Select("withInstall")

	return &PythonSDKRuntime{
		query: q,
	}
}

// Add the module's source code
func (r *PythonSDKRuntime) WithSource() *PythonSDKRuntime {
	q := r.query.Select("withSource")

	return &PythonSDKRuntime{
		query: q,
	}
}

// Enable the use of uv
func (r *PythonSDKRuntime) WithUv() *PythonSDKRuntime {
	q := r.query.Select("withUv")

	return &PythonSDKRuntime{
		query: q,
	}
}

// Override the uv version
//
// Needs to be called before Load. Enables uv if not already enabled.
func (r *PythonSDKRuntime) WithUvVersion(version string) *PythonSDKRuntime {
	q := r.query.Select("withUvVersion")
	q = q.Arg("version", version)

	return &PythonSDKRuntime{
		query: q,
	}
}

// Disable the discovery of custom configuration
//
// If it's not necessary, it's faster without it.
func (r *PythonSDKRuntime) WithoutUserConfig() *PythonSDKRuntime {
	q := r.query.Select("withoutUserConfig")

	return &PythonSDKRuntime{
		query: q,
	}
}

// Disable the use of uv
func (r *PythonSDKRuntime) WithoutUv() *PythonSDKRuntime {
	q := r.query.Select("withoutUv")

	return &PythonSDKRuntime{
		query: q,
	}
}

func (r *Query) PythonSDKRuntime() *PythonSDKRuntime { // python-sdk-runtime (../../../:0:0)
	q := r.query.Select("pythonSdkRuntime")

	return &PythonSDKRuntime{
		query: q,
	}
}
