// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// State threaded through the steps that build a module's runtime container.
//
// ModuleRuntime is the only thing the engine calls; everything else here is
// internal to it.
type PythonSDKRuntime struct { // python-sdk-runtime (../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *PythonSDKRuntime) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKRuntime {
	return &PythonSDKRuntime{
		query: q,
	}
}

// A unique identifier for this PythonSdkRuntime.
func (r *PythonSDKRuntime) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKRuntime) XXX_GraphQLType() string {
	return "PythonSdkRuntime"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKRuntime) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKRuntime) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKRuntime) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKRuntime) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PythonSDKRuntime{query: selectNode(dag.query, id, "PythonSdkRuntime")}
	return nil
}

// PythonSDKRuntimeModuleRuntimeOpts contains options for PythonSDKRuntime.ModuleRuntime
type PythonSDKRuntimeModuleRuntimeOpts struct {
	IntrospectionJSON *File
}

// Container for executing the Python module runtime
//
// The container is built from the module's committed generated files. This
// runtime generates nothing: code generation belongs to `dagger generate`,
// which the Python SDK module owns. Dependencies are still installed — the
// language-level assemble step, like the Go SDK still running go build.
//
// introspectionJSON is declared, and never read, on purpose: its optionality is
// the signal the engine reads (RuntimeTrustsCommittedFiles) to decide it may
// skip runtime codegen and omit the argument altogether. Dropping the argument
// would tell the engine the opposite. It is the opt-out, not a code path.
func (r *PythonSDKRuntime) ModuleRuntime(modSource *ModuleSource, opts ...PythonSDKRuntimeModuleRuntimeOpts) *Container {
	assertNotNil("modSource", modSource)
	q := r.query.Select("moduleRuntime")
	for i := len(opts) - 1; i >= 0; i-- {
		// `introspectionJson` optional argument
		if !querybuilder.IsZeroValue(opts[i].IntrospectionJSON) {
			q = q.Arg("introspectionJson", opts[i].IntrospectionJSON)
		}
	}
	q = q.Arg("modSource", modSource)

	return &Container{
		query: q,
	}
}

func (r *Query) PythonSDKRuntime() *PythonSDKRuntime { // python-sdk-runtime (../../../:0:0)
	q := r.query.Select("pythonSdkRuntime")

	return &PythonSDKRuntime{
		query: q,
	}
}
