"""One package per client, plus one for core, in `dagger_clients`."""

import json
import pathlib
import textwrap
from collections.abc import Iterator
from itertools import groupby

from graphql import (
    GraphQLField,
    GraphQLInterfaceType,
    GraphQLObjectType,
    GraphQLSchema,
    GraphQLType,
    Node,
    get_named_type,
)
from graphql.type.schema import TypeMap

from codegen import partition
from codegen.generator import (
    Context,
    _ObjectField,
    expected_type_name,
    format_name,
    indent,
    is_builtin_scalar_type,
    is_input_object_type,
    is_interface_type,
    is_object_type,
    joiner,
    legacy_id_names,
    new_context,
    quote,
    render_types,
)

NAMESPACE = "dagger_clients"
"""Namespace package that every generated package goes into."""

Files = dict[str, str]
"""Content of a package, by file name."""

_HEADER = """\
# Code generated by dagger. DO NOT EDIT.

import warnings  # noqa: F401
from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, overload, runtime_checkable

from typing_extensions import Self

from dagger.client import %s
from dagger.client._core import Arg
from dagger.client._guards import type_error as _type_error
from dagger.client.base import Enum, Input, Root, Scalar, Type
"""


class _EntryField(_ObjectField):
    """Field of `Query` that is the way into a client."""

    def __init__(
        self,
        ctx: Context,
        name: str,
        field: GraphQLField,
        parent: GraphQLObjectType | GraphQLInterfaceType,
    ) -> None:
        super().__init__(ctx, name, field, parent)
        for arg in self.args:
            if arg.name == "session":
                arg.name = "session_"

    @property
    def label(self) -> str:
        return self.name

    @property
    def return_type(self) -> str:
        return self.type

    def params(self) -> Iterator[str]:
        yield from (a.as_param() for a in self.required_args)
        yield "*"
        yield from (a.as_param() for a in self.default_args)
        yield "session: Session | None = None"

    @joiner
    def func_body(self) -> Iterator[str]:
        yield from self.func_prelude()
        yield (
            f"return client_root({self.type}, TARGET, "
            f'"{self.graphql_name}", _args, session=session)'
        )

    def render(self) -> str:
        return _block(self.func_signature(), indent(self.func_body()))


class _ContributedField(_ObjectField):
    """Field that a client contributes to a core type, as a function."""

    def __init__(
        self,
        ctx: Context,
        name: str,
        field: GraphQLField,
        parent: GraphQLObjectType | GraphQLInterfaceType,
    ) -> None:
        super().__init__(ctx, name, field, parent)
        self.receiver = format_name(parent.name)
        if self.receiver in {arg.name for arg in self.args}:
            self.receiver += "_"
        for arg in self.args:
            # A function has no `Self` to name the receiver's type with.
            arg.is_self = False

    @property
    def label(self) -> str:
        return self.name

    @property
    def return_type(self) -> str:
        return self.type

    @property
    def private_name(self) -> str:
        """Name of the function when the public one dispatches on the receiver."""
        return f"_{self.receiver}_{self.name}"

    def params(self) -> Iterator[str]:
        # Positional only, because the name changes with the receiver's type
        # when the function is overloaded.
        yield f"{self.receiver}: {self.parent_name}"
        yield "/"
        yield from list(super().params())[1:]

    def select_expr(self) -> str:
        return f'client_select({self.receiver}, TARGET, "{self.graphql_name}", _args)'

    def render(self, name: str | None = None) -> str:
        return _block(self.func_signature(name), indent(self.func_body()))


def _block(*lines: str) -> str:
    """A top level statement, with the blank lines that set it apart."""
    return "\n".join(("", *lines, ""))


def _render_overloaded(name: str, fields: list[_ContributedField]) -> Iterator[str]:
    yield from (f.render(f.private_name) for f in fields)
    yield from (_block("@overload", f"{f.func_signature()} ...") for f in fields)

    expected = " | ".join(f.parent_name for f in fields)
    yield _block(
        f"def {name}(receiver, /, *args, **kwargs):",
        *(
            indent(
                f"if isinstance(receiver, {f.parent_name}):\n"
                f"    return {f.private_name}(receiver, *args, **kwargs)"
            )
            for f in fields
        ),
        indent(f'raise _type_error("{name}", "receiver", receiver, "{expected}")'),
    )


def _owned(schema: GraphQLSchema, module: str | None) -> TypeMap:
    return {
        name: t
        for name, t in schema.type_map.items()
        if partition.source_module(t.ast_node) == module
    }


def _all(names: list[str]) -> str:
    return _block(
        "__all__ = [",
        *(indent(f"{quote(name)},") for name in sorted(names)),
        "]",
    )


@joiner
def _core_init(schema: GraphQLSchema, schema_version: str) -> Iterator[str]:
    ctx = new_context(schema, schema_version, partitioned=True)
    digest = partition.core_digest(schema, schema_version)

    yield _HEADER % "Session, client_root"
    yield from render_types(ctx, _owned(schema, None))
    yield _block(
        "def core(*, session: Session | None = None) -> Query:",
        indent('"""The way into the core API."""'),
        indent("return client_root(Query, None, None, [], session=session)"),
    )
    yield _block(
        f"CORE_DIGEST = {quote(digest)}",
        '"""Digest of the core schema that this package was generated from."""',
    )
    yield _all([*ctx.defined, "CORE_DIGEST", "core"])


def _core_names(ctx: Context) -> set[str]:
    """Every name that a client may import from the core package."""
    core = _owned(ctx.schema, None)
    names = set(legacy_id_names(ctx.schema, core)) if ctx.legacy_sdk_compat else set()
    for name, t in core.items():
        if name.startswith("_") or is_builtin_scalar_type(t):
            continue
        names.add(name)
        if is_interface_type(t):
            names.add(f"_{name}Client")
    return names


def _find_module(schema: GraphQLSchema, name: str) -> tuple[str, str]:
    """The module of the schema that a client name stands for, and its package."""
    package = partition.package_name(name)
    packages = partition.package_names(partition.modules(schema))
    for module, module_package in packages.items():
        if module_package == package:
            return module, package
    msg = (
        f'the schema attributes nothing to the client "{name}"; '
        f"it has: {', '.join(packages) or 'no module'}"
    )
    raise partition.ClientError(msg)


def _references(schema: GraphQLSchema, module: str, owned: TypeMap) -> dict[str, str]:
    """Types that the code of a client names, and one place that names each."""
    places: list[tuple[str, GraphQLType, Node | None]] = []
    members = [
        (t, name, f)
        for t in owned.values()
        if is_object_type(t) or is_interface_type(t)
        for name, f in t.fields.items()
    ]
    for parent, name, f in [*partition.contributed_fields(schema, module), *members]:
        place = f"{parent.name}.{name}"
        places.append((place, f.type, f.ast_node))
        places += [(place, a.type, a.ast_node) for a in f.args.values()]
    for t in owned.values():
        if is_input_object_type(t):
            places += [
                (f"{t.name}.{name}", i.type, i.ast_node) for name, i in t.fields.items()
            ]

    names: dict[str, str] = {}
    for place, type_, node in places:
        names.setdefault(get_named_type(type_).name, place)
        if expected := expected_type_name(schema, node):
            names.setdefault(expected, place)
    return names


def _core_imports(ctx: Context, module: str, references: dict[str, str]) -> list[str]:
    """Names to import from core, refusing a name that another client owns."""
    available = _core_names(ctx)
    imports = set()
    for name, place in references.items():
        t = ctx.schema.get_type(name)
        owner = partition.source_module(t.ast_node) if t else None
        if owner not in (None, module):
            msg = (
                f'"{place}" of the client "{module}" names '
                f'"{name}" of the client "{owner}"'
            )
            raise partition.ClientError(msg)
        # The legacy ID and the concrete class of an interface go along with
        # the type, because the code that uses the type may use them too.
        imports |= {name, f"{name}ID", f"_{name}Client"} & available
    return sorted(imports)


@joiner
def _client_init(
    schema: GraphQLSchema, module: str, package: str, schema_version: str
) -> Iterator[str]:
    ctx = new_context(schema, schema_version, partitioned=True)
    owned = _owned(schema, module)

    entry: _EntryField | None = None
    contributed: list[_ContributedField] = []
    for parent, name, field in partition.contributed_fields(schema, module):
        # The entry is the `Query` field that the module contributes under its
        # own name, because that is the constructor the engine makes for it.
        # Any other `Query` field it contributes is a plain function.
        if parent.name == "Query" and name.lower() == package.replace("_", ""):
            entry = _EntryField(ctx, name, field, parent)
        else:
            contributed.append(_ContributedField(ctx, name, field, parent))

    if entry is None or not is_object_type(entry.named_type):
        msg = f'the schema has no constructor for the client "{module}"'
        raise partition.ClientError(msg)

    references = _references(schema, module, owned)
    references |= {f.parent_name: f.label for f in contributed}

    yield _HEADER.rstrip() % "Session, Target, check_core, client_root, client_select"
    yield f"from {NAMESPACE}.{partition.CORE} import ("
    yield indent("CORE_DIGEST as _installed_core,")
    yield from (indent(f"{name},") for name in _core_imports(ctx, module, references))
    yield ")"
    yield ""
    yield "from ._target import CORE_DIGEST, NAME, PIN, REF"
    yield ""
    # Before anything else, so that a stale client fails on its import line.
    yield "check_core(NAME, CORE_DIGEST, _installed_core)"
    yield _block(
        "TARGET = Target(name=NAME, ref=REF, pin=PIN)",
        '"""The module that this client loads on first use."""',
    )
    yield from _client_body(ctx, owned, entry, contributed)


def _client_body(
    ctx: Context,
    owned: TypeMap,
    entry: _EntryField,
    contributed: list[_ContributedField],
) -> Iterator[str]:
    yield from render_types(ctx, owned)
    yield entry.render()

    functions = [entry.name]
    by_name = sorted(contributed, key=lambda f: (f.name, f.parent_name))
    for name, group in groupby(by_name, key=lambda f: f.name):
        fields = list(group)
        functions.append(name)
        if len(fields) == 1:
            yield fields[0].render()
        else:
            yield from _render_overloaded(name, fields)

    yield _all([*ctx.defined, *functions])


def _target(name: str, ref: str, pin: str | None, core_digest: str) -> str:
    # Plain data, so that reading the descriptor never needs the SDK.
    return textwrap.dedent(
        f"""\
        # Code generated by dagger. DO NOT EDIT.

        NAME = {json.dumps(name)}
        REF = {json.dumps(ref)}
        PIN = {json.dumps(pin) if pin else None}
        CORE_DIGEST = {json.dumps(core_digest)}
        """
    )


def core_package(schema: GraphQLSchema, schema_version: str = "") -> Files:
    """Files of `dagger_clients.core`, whatever clients the schema holds."""
    return {
        "__init__.py": _core_init(schema, schema_version),
        "py.typed": "",
    }


def client_package(  # noqa: PLR0913
    schema: GraphQLSchema,
    name: str,
    ref: str,
    pin: str | None = None,
    core_digest: str | None = None,
    schema_version: str = "",
) -> tuple[str, Files]:
    """Package name and files of one client, whatever the other clients are."""
    module, package = _find_module(schema, name)
    if core_digest is None:
        core_digest = partition.core_digest(schema, schema_version)
    return package, {
        "__init__.py": _client_init(schema, module, package, schema_version),
        "_target.py": _target(name, ref, pin, core_digest),
        "py.typed": "",
    }


def write_package(output: pathlib.Path, package: str, files: Files) -> pathlib.Path:
    """Write a package under the namespace, which itself gets no `__init__.py`."""
    root = output / NAMESPACE / package
    root.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (root / name).write_text(content)
    return root
