name = "engine-e2e"
engineVersion = "v1.0.0-0"

[runtime]
  source = "dang"

[[dependencies]]
  name = "engine-dev"
  source = "github.com/dagger/dagger/.dagger/modules/engine-dev@6f0625319587865054377d0e03690424e3e8b861"
