name = "engine-e2e"
engineVersion = "v1.0.0-0"

[runtime]
  source = "dang"

[[dependencies]]
  name = "engine-dev"
  source = "github.com/dagger/dagger/.dagger/modules/engine-dev@4693aa406c117025ba285cdaba6863f486a328c2"
